name: Deploy Portfolio to AWS S3

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
      - 'style.css'
      - 'script.js'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Secrets
      run: |
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "❌ AWS_ACCESS_KEY_ID not found"
          exit 1
        else
          echo "✅ AWS_ACCESS_KEY_ID is set"
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy static site to S3
      run: |
        aws s3 sync . s3://vishal-portfolio-site \
          --delete --exclude ".git/*" --exclude ".github/*" \
          --exclude "Dockerfile"
